spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://192.168.0.120:3306/steelStorage?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=Europe/Sofia"
    username: test
    password: 12345
#    url: "jdbc:mysql://localhost:3306/steelStorage?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=Europe/Sofia"
#    username: root
#    password: 12345
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 25MB
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  sql:
    init:
      mode: never
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  thymeleaf: # Thymeleaf
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: file:src/main/resources/templates/
  web:
    resources:
      static-locations: file:src/main/resources/static/
      cache:
        period: 0

steel storage:
  remember.me.key: 1412324
logging:
  level:
    #    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: INFO
    org.springframework.security: INFO
#    org.apache.coyote.http11.Http11Processor: DEBUG
#    org.apache.tomcat.util.net: DEBUG


server:
  port: 8182
